<ips:template parameters="$requirements, $incorrectFiles" />
{{$canProceed = TRUE;}}
<section class='ipsInstaller__padding'>
	{{if $incorrectFiles !== NULL}}
		{{if $incorrectFiles}}
			{{$canProceed = FALSE;}}
			<h2 class="ipsType_pageTitle i-margin-bottom_1">{lang="hc_files"}</h2>
			<p>{lang="hc_files_fail"}</p>
			<div class="i-margin-top_3 i-margin-bottom_3">
				<a class="ipsButton ipsButton--primary" href='{url="client_area" ips="true"}' target="_blank" rel="noopener">{lang="hc_files_fail2"}</a>
			</div>
			<p>{lang="hc_files_fail3"}</p>
			<ul class="i-margin-top_3 ipsList_checks">
				{{foreach $incorrectFiles as $file}}
					<li class="fail">{$file}</li>
				{{endforeach}}
			</ul>
		{{else}}
			<h2 class="ipsType_pageTitle i-margin-bottom_1">{lang="hc_files"}</h2>
			<ul class="ipsList_checks">
				<li class="success">{lang="hc_files_ok"}</li>
			</ul>
		{{endif}}
	{{endif}}
	{{foreach $requirements['requirements'] as $k => $_requirements}}
		<h2 class="ipsType_pageTitle i-margin-bottom_1">{lang="hc_requirements" sprintf="$k"}</h2>
		<ul class="ipsList_checks">
			{{foreach $_requirements as $item}}
				{{if !$item['success']}}{{$canProceed = FALSE;}}{{endif}}
				<li class="{{if $item['success']}}success{{else}}fail{{endif}}">{$item['message']}</li>
			{{endforeach}}
		</ul>
	{{endforeach}}
	{{if isset( $requirements['advice'] ) and \count( $requirements['advice'] )}}
		<h2 class="ipsType_pageTitle i-margin-bottom_1">{lang="hc_recommendations"}</h2>
		<p>{lang="hc_recommendations_info"}</p>
		<ul class="ipsList_checks i-margin-top_2">
			{{foreach $requirements['advice'] as $items}}
				{{foreach $items as $key => $item}}
					<li class="{{if $key === 'php'}}ipsMessage ipsMessage--warning{{else}}advisory{{endif}}">{$item}</li>
				{{endforeach}}
			{{endforeach}}
		</ul>
	{{endif}}
</section>

<div class='i-padding_4 i-text-align_center'>
	{{if $canProceed}}
		<a href='{url="controller=license&key={$_SESSION['uniqueKey']}"}' class='ipsButton ipsButton--large ipsButton--primary'>{lang="continue"}</a>
	{{else}}
		<a href='' class='ipsButton ipsButton--large ipsButton--primary ipsButton--disabled'>{lang="hc_no_continue"}</a>
	{{endif}}
</div>